# Generated by Django 5.0.14 on 2026-06-08 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Mata Pelajaran',
                'verbose_name_plural': 'Mata Pelajaran',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tahun Ajaran')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Tidak Aktif')], default='aktif', max_length=10, verbose_name='Status')),
                ('tanggal_mulai', models.DateField(verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(verbose_name='Tanggal Selesai')),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Kelas')),
                ('tingkat', models.CharField(choices=[('X', 'X'), ('XI', 'XI'), ('XII', 'XII')], max_length=5, verbose_name='Tingkat')),
                ('wali_kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_perwalian', to=settings.AUTH_USER_MODEL, verbose_name='Wali Kelas')),
            ],
            options={
                'verbose_name': 'Kelas',
                'verbose_name_plural': 'Kelas',
                'ordering': ['tingkat', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10, verbose_name='Nama Semester')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Tidak Aktif')], default='aktif', max_length=10, verbose_name='Status')),
                ('tanggal_mulai', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai')),
                ('tanggal_selesai', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academic.tahunajaran', verbose_name='Tahun Ajaran')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
                'ordering': ['tahun_ajaran', 'name'],
                'unique_together': {('name', 'tahun_ajaran')},
            },
        ),
    ]
