# Generated by Django 5.0.14 on 2026-06-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matapelajaran',
            name='kode',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Kode Mata Pelajaran'),
        ),
    ]
