# Generated by Django 5.0.14 on 2026-06-08 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_matapelajaran_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kelas',
            name='tahun_ajaran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academic.tahunajaran', verbose_name='Tahun Ajaran'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nama Kelas'),
        ),
        migrations.AlterUniqueTogether(
            name='kelas',
            unique_together={('name', 'tahun_ajaran')},
        ),
    ]
