# Generated by Django 5.0.14 on 2026-06-08 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalPertemuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tanggal Pertemuan')),
                ('agenda', models.CharField(max_length=200, verbose_name='Agenda/Topik Bahasan')),
                ('material_summary', models.TextField(verbose_name='Ringkasan Materi')),
                ('present_count', models.IntegerField(verbose_name='Jumlah Siswa Hadir')),
                ('absent_count', models.IntegerField(verbose_name='Jumlah Siswa Absen')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL, verbose_name='Guru Pengajar')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='academic.kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='academic.matapelajaran', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Jurnal Pertemuan',
                'verbose_name_plural': 'Jurnal Pertemuan',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
