# Generated by Django 5.0.14 on 2026-06-08 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermintaanKoreksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel_name', models.CharField(max_length=100, verbose_name='Nama Mata Pelajaran')),
                ('status_semula', models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], max_length=10, verbose_name='Status Semula')),
                ('status_koreksi', models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], max_length=10, verbose_name='Status Koreksi')),
                ('keterangan', models.TextField(verbose_name='Alasan Koreksi')),
                ('verified', models.BooleanField(default=False, verbose_name='Terverifikasi')),
                ('tanggal', models.DateField(verbose_name='Tanggal Absensi')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='koreksi_presensi', to='academic.kelas', verbose_name='Kelas')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='koreksi_presensi', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Permintaan Koreksi',
                'verbose_name_plural': 'Permintaan Koreksi',
                'ordering': ['-tanggal', 'siswa'],
            },
        ),
        migrations.CreateModel(
            name='AbsensiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='Tanggal')),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], default='Hadir', max_length=10, verbose_name='Status Kehadiran')),
                ('status_awal', models.CharField(blank=True, choices=[('Hadir', 'Hadir'), ('Sakit', 'Sakit'), ('Izin', 'Izin'), ('Alpa', 'Alpa')], max_length=10, null=True, verbose_name='Status Awal (Sebelum Override)')),
                ('keterangan', models.TextField(blank=True, null=True, verbose_name='Keterangan')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='academic.kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absensi', to='academic.matapelajaran', verbose_name='Mata Pelajaran')),
                ('siswa', models.ForeignKey(limit_choices_to={'role': 'siswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
            ],
            options={
                'verbose_name': 'Absensi Siswa',
                'verbose_name_plural': 'Absensi Siswa',
                'ordering': ['-tanggal', 'kelas', 'siswa'],
                'unique_together': {('siswa', 'kelas', 'mapel', 'tanggal')},
            },
        ),
    ]
