# Generated by Django 5.0.14 on 2026-06-08 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=2, null=True, verbose_name='Jenis Kelamin'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pengampu',
            field=models.BooleanField(default=False, verbose_name='Penugasan Pengampu'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_piket_today',
            field=models.BooleanField(default=False, verbose_name='Piket Hari Ini'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_wali_kelas',
            field=models.BooleanField(default=False, verbose_name='Wali Kelas (Cadangan)'),
        ),
        migrations.AddField(
            model_name='user',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academic.kelas', verbose_name='Kelas (Siswa)'),
        ),
        migrations.AddField(
            model_name='user',
            name='nip_or_nis',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP / NIS'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Telepon'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Pengajuan')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
