# Generated by Django 5.0.14 on 2026-06-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender_user_is_pengampu_user_is_piket_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='angkatan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Angkatan'),
        ),
    ]
