# Generated by Django 5.0.14 on 2026-06-08 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Materi')),
                ('description', models.TextField(verbose_name='Deskripsi Materi')),
                ('source_type', models.CharField(choices=[('link', 'Link'), ('file', 'File')], max_length=10, verbose_name='Tipe Sumber')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Berkas/Tautan')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dipublikasikan', 'Dipublikasikan')], default='Draft', max_length=20, verbose_name='Status Publikasi')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi_diajar', to=settings.AUTH_USER_MODEL, verbose_name='Guru Pengajar')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='academic.kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='academic.matapelajaran', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Materi',
                'verbose_name_plural': 'Materi',
                'ordering': ['-date_created', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Judul Tugas')),
                ('description', models.TextField(verbose_name='Deskripsi Tugas')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Lampiran Tugas')),
                ('due_date', models.DateField(verbose_name='Batas Tenggat Waktu')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Tanggal Dibuat')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dipublikasikan', 'Dipublikasikan')], default='Draft', max_length=20, verbose_name='Status Publikasi')),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_diberikan', to=settings.AUTH_USER_MODEL, verbose_name='Guru Pembuat')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='academic.kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='academic.matapelajaran', verbose_name='Mata Pelajaran')),
            ],
            options={
                'verbose_name': 'Tugas',
                'verbose_name_plural': 'Tugas',
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_date', models.DateField(auto_now_add=True, verbose_name='Tanggal Pengumpulan')),
                ('file_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL Jawaban Berkas/Tautan')),
                ('status', models.CharField(choices=[('Belum Mengumpulkan', 'Belum Mengumpulkan'), ('Terkumpul', 'Terkumpul'), ('Late', 'Late')], default='Belum Mengumpulkan', max_length=20, verbose_name='Status Pengumpulan')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='Nilai')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Umpan Balik Guru')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Siswa')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.tugas', verbose_name='Tugas')),
            ],
            options={
                'verbose_name': 'Pengumpulan Tugas',
                'verbose_name_plural': 'Pengumpulan Tugas',
                'unique_together': {('tugas', 'siswa')},
            },
        ),
    ]
