# Generated by Django 5.0.14 on 2026-06-08 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10, verbose_name='Hari')),
                ('waktu_mulai', models.TimeField(verbose_name='Waktu Mulai')),
                ('waktu_selesai', models.TimeField(verbose_name='Waktu Selesai')),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_mengajar', to=settings.AUTH_USER_MODEL, verbose_name='Guru Pengampu')),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_pelajaran', to='academic.kelas', verbose_name='Kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_pelajaran', to='academic.matapelajaran', verbose_name='Mata Pelajaran')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_pelajaran', to='academic.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Jadwal Pelajaran',
                'verbose_name_plural': 'Jadwal Pelajaran',
                'ordering': ['semester', 'hari', 'waktu_mulai'],
            },
        ),
        migrations.CreateModel(
            name='JadwalPiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10, verbose_name='Hari Tugas')),
                ('guru', models.ForeignKey(limit_choices_to={'role': 'guru'}, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_piket', to=settings.AUTH_USER_MODEL, verbose_name='Guru Piket')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_piket', to='academic.semester', verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Jadwal Piket',
                'verbose_name_plural': 'Jadwal Piket',
                'ordering': ['semester', 'hari', 'guru'],
            },
        ),
    ]
