import React, { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth";
import { scheduleService } from "@/services/scheduleService";
import { userService } from "@/services/userService";
import { attendanceService } from "@/services/attendanceService";
import type { JadwalPembelajaran } from "@/types/schedule";
import type { UserDetail } from "@/types/user";
import type { AbsensiSiswa, StatusKehadiran } from "@/types/attendance";
import { getActiveDateString } from "@/utils/student";
import {
  DataTable,
  Button,
  Toast,
  LoadingState,
  Select,
  Input,
} from "@/components/shared";
import { CheckCircle } from "lucide-react";

export const AttendancePage: React.FC = () => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [schedules, setSchedules] = useState<JadwalPembelajaran[]>([]);
  const [selectedScheduleId, setSelectedScheduleId] = useState("");
  const [tanggal, setTanggal] = useState(getActiveDateString());
  const [students, setStudents] = useState<UserDetail[]>([]);
  const [attendanceRecords, setAttendanceRecords] = useState<
    Record<string, { status: StatusKehadiran; keterangan: string }>
  >({});
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  useEffect(() => {
    const fetchInitialData = async () => {
      if (!user) return;
      setLoading(true);
      try {
        const schData = await scheduleService.getJadwalPembelajaran();
        const mySch = schData.filter(
          (s) => String(s.guruId) === String(user.id),
        );
        setSchedules(mySch);
        if (mySch.length > 0) {
          setSelectedScheduleId(mySch[0].id);
        }
      } catch (err) {
        setToastMessage(
          err instanceof Error ? err.message : "Gagal memuat jadwal mengajar.",
        );
      } finally {
        setLoading(false);
      }
    };
    fetchInitialData();
  }, [user]);

  // Load students and their current attendance records for selected class/date
  useEffect(() => {
    const loadClassAttendance = async () => {
      if (!selectedScheduleId) return;
      const currentSch = schedules.find((s) => s.id === selectedScheduleId);
      if (!currentSch) return;

      try {
        const [allUsers, existingAbs] = await Promise.all([
          userService.getAll(),
          attendanceService.getAbsensiSiswaByKelas(currentSch.kelasId, tanggal),
        ]);

        // Filter students in the target class
        const finalStudents = allUsers.filter(
          (u) =>
            u.role === "siswa" &&
            String(u.kelasId) === String(currentSch.kelasId),
        );

        setStudents(finalStudents);

        // Pre-fill attendance states
        const initialStates: Record<
          string,
          { status: StatusKehadiran; keterangan: string }
        > = {};
        finalStudents.forEach((student) => {
          const match = existingAbs.find(
            (a) => a.siswaId === student.id && a.mapelId === currentSch.mapelId,
          );
          initialStates[student.id] = {
            status: match ? match.status : "Hadir",
            keterangan: match ? match.keterangan || "" : "",
          };
        });
        setAttendanceRecords(initialStates);
      } catch (err) {
        setToastMessage(
          err instanceof Error ? err.message : "Gagal memuat data absensi.",
        );
      }
    };
    loadClassAttendance();
  }, [selectedScheduleId, schedules, tanggal]);

  const handleStatusChange = (studentId: string, status: StatusKehadiran) => {
    setAttendanceRecords((prev) => ({
      ...prev,
      [studentId]: {
        ...prev[studentId],
        status,
      },
    }));
  };

  const handleSave = async () => {
    const currentSch = schedules.find((s) => s.id === selectedScheduleId);
    if (!currentSch) return;

    const recordsToSubmit: AbsensiSiswa[] = students.map((student) => {
      const state = attendanceRecords[student.id] || {
        status: "Hadir",
        keterangan: "",
      };
      return {
        id: "", // generated by service
        siswaId: student.id,
        siswaName: student.name,
        nis: student.nipOrNis || "",
        kelasId: currentSch.kelasId,
        kelasName: currentSch.kelasName,
        mapelId: currentSch.mapelId,
        mapelName: currentSch.mapelName,
        tanggal,
        status: state.status,
        keterangan: state.keterangan,
      };
    });

    try {
      await attendanceService.submitAbsensiSiswa(recordsToSubmit);
      setToastMessage("Kehadiran kelas berhasil disimpan!");
    } catch {
      setToastMessage("Gagal menyimpan absensi.");
    }
  };

  const columns = [
    {
      header: "NIS",
      cell: (s: UserDetail) => (
        <span className="text-[12px] font-mono text-bg-ink-muted font-bold">
          {s.nipOrNis}
        </span>
      ),
    },
    {
      header: "Nama Siswa",
      cell: (s: UserDetail) => (
        <span className="text-[13px] font-semibold text-bg-ink">{s.name}</span>
      ),
    },
    {
      header: "Presensi",
      cell: (s: UserDetail) => {
        const currentRecord = attendanceRecords[s.id] || {
          status: "Hadir",
          keterangan: "",
        };
        return (
          <div className="flex items-center gap-1.5">
            {(["Hadir", "Sakit", "Izin", "Alpa"] as StatusKehadiran[]).map(
              (st) => {
                const isActive = currentRecord.status === st;
                const isHadir = st === "Hadir";

                const buttonStyles = isActive
                  ? st === "Hadir"
                    ? "bg-primary text-white border-primary cursor-pointer"
                    : st === "Sakit"
                      ? "bg-status-info text-white border-status-info cursor-not-allowed opacity-80"
                      : st === "Izin"
                        ? "bg-status-warning text-white border-status-warning cursor-not-allowed opacity-80"
                        : "bg-status-danger text-white border-status-danger cursor-not-allowed opacity-80"
                  : isHadir
                    ? "bg-bg-surface hover:bg-bg-sage-slate text-bg-ink-secondary border-bg-border cursor-pointer"
                    : "bg-bg-sage-slate/40 text-bg-ink-muted/50 border-bg-border/30 cursor-not-allowed";

                return (
                  <button
                    key={st}
                    disabled={!isHadir}
                    onClick={() => handleStatusChange(s.id, st)}
                    aria-pressed={isActive}
                    aria-label={`Tandai ${s.name} ${st}`}
                    className={`px-3.5 py-1.5 text-[11px] font-bold border rounded-[6px] transition-all active:scale-[0.96] focus-visible:outline-none ${buttonStyles}`}
                  >
                    {st}
                  </button>
                );
              },
            )}
          </div>
        );
      },
    },
    {
      header: "Keterangan",
      cell: (s: UserDetail) => {
        const currentRecord = attendanceRecords[s.id] || {
          status: "Hadir",
          keterangan: "",
        };
        const isDisabled = true; // Subject teacher cannot edit notes since non-Hadir status is handled by Piket
        return (
          <input
            type="text"
            id={`ket-${s.id}`}
            value={currentRecord.keterangan}
            disabled={isDisabled}
            placeholder={
              currentRecord.status === "Hadir"
                ? "Tidak ada catatan"
                : currentRecord.keterangan || "Tidak ada keterangan dari piket"
            }
            aria-label={`Keterangan absen untuk ${s.name}`}
            className="block w-full max-w-xs rounded-[6px] border border-bg-border bg-bg-surface text-bg-ink px-2.5 py-1.5 text-[12px] placeholder:text-bg-ink-muted focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-primary disabled:opacity-50 disabled:bg-bg-sage-slate/20"
          />
        );
      },
    },
  ];

  const currentSch = schedules.find((s) => s.id === selectedScheduleId);

  return (
    <div className="space-y-6">
      {toastMessage && (
        <Toast
          message={toastMessage}
          variant="safe"
          onClose={() => setToastMessage(null)}
        />
      )}

      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-[32px] font-bold leading-tight tracking-tight text-bg-ink font-sans">
            Presensi Kelas
          </h1>
          <p className="mt-1 text-[13px] text-bg-ink-secondary leading-snug">
            Catat dan perbarui absensi siswa berdasarkan jadwal mengajar aktif
            Anda.
          </p>
        </div>
        {currentSch && (
          <Button className="gap-2" onClick={handleSave}>
            <CheckCircle className="h-4 w-4" />
            Simpan Absensi
          </Button>
        )}
      </div>

      {/* Filters selectors */}
      <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 bg-bg-surface border border-bg-border rounded-[6px] p-4">
        <div className="flex-1 flex flex-col sm:flex-row gap-3">
          <div className="flex-1">
            <label className="block text-[13px] font-semibold text-bg-ink-secondary mb-1.5 font-sans">
              Sesi Kelas & Mata Pelajaran
            </label>
            {schedules.length === 0 ? (
              <Select disabled>
                <option>Tidak ada jadwal mengajar</option>
              </Select>
            ) : (
              <Select
                value={selectedScheduleId}
                onChange={(e) => setSelectedScheduleId(e.target.value)}
              >
                {schedules.map((s) => (
                  <option key={s.id} value={s.id}>
                    [{s.hari}] {s.kelasName} - {s.mapelName} ({s.waktuMulai} -{" "}
                    {s.waktuSelesai})
                  </option>
                ))}
              </Select>
            )}
          </div>

          <div className="w-full sm:w-[180px]">
            <label className="block text-[13px] font-semibold text-bg-ink-secondary mb-1.5 font-sans">
              Tanggal Presensi
            </label>
            <Input
              type="date"
              value={tanggal}
              onChange={(e) => setTanggal(e.target.value)}
            />
          </div>
        </div>
      </div>

      {loading ? (
        <LoadingState message="Memuat jadwal mengajar..." />
      ) : !currentSch ? (
        <div className="border border-bg-border bg-bg-surface rounded-[6px] p-8 text-center">
          <p className="text-[14px] font-bold text-bg-ink">
            Belum Ada Sesi Kelas
          </p>
          <p className="mt-1 text-[13px] text-bg-ink-secondary">
            Anda tidak terdaftar mengajar di kelas manapun hari ini.
          </p>
        </div>
      ) : (
        <DataTable
          title={`Presensi Kelas ${currentSch.kelasName} — Mapel: ${currentSch.mapelName}`}
          columns={columns}
          data={students}
          keyExtractor={(s) => s.id}
        />
      )}
    </div>
  );
};
export default AttendancePage;
